### PR TITLE
Remove hardcoding of expected macOS versions

### LINKED ISSUE #101: `generate_cask` task failing since June 17th, 19:05 GMT-4
See https://dev.azure.com/foolip/safari-technology-preview-updater/_build?definitionId=12&_a=summary

Example failure: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=3275&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5852bf5a-5a02-52f3-bee8-4fdc90cda9d0

```
Starting: generate cask
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
node gen-cask.js
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/4c8b6d0e-8f2f-43ba-ac50-b05ef4a21712.sh
Error: Expecting Catalina + Big Sur packages but got {"monterey":{"url":"https://secure-appldnld.apple.com/STP/001-66930-20210616-c91fc8a5-bfeb-47ec-80c2-0d54c6ebbcee/SafariTechnologyPreview.dmg","sha256":"d7547c77c709db6f551a5be1c60fcdff3b116579aa24038ebe2936003e8c3af4"},"big_sur":{"url":"https://secure-appldnld.apple.com/STP/071-49115-20210616-CFF65F23-A558-4BE9-BC39-636914359EBC/SafariTechnologyPreview.dmg","sha256":"6896b6db3f25937a85dc6827b0e65f8e04f868fc2a8d38bbc7c86f342bb4363b"}}
    at generateCask (/Users/runner/work/1/s/gen-cask.js:64:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
##[error]Bash exited with code '1'.
Finishing: generate cask
```

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/foolip/safari-technology-preview-updater/issues/101.

### CODE REVIEW

**Comment by foolip** [comment]
@stephenmcgruer care to review?

**Comment by foolip** [comment]
So, this isn't actually going to fix the scheduled jobs, because they also try installing the generated cask to get the version string out of it.

**Review by stephenmcgruer — APPROVED** [review]
I didn't verify the exact cask generated, and I'm not sure how much we should assume that the last OS listed is the oldest, but this seems ok enough to me.

(I might be tempted instead to continue to hard-code versions into the script, and pay the price of updating them when Mac has new version names. But it's your script :))

**Comment by foolip** [comment]
> I might be tempted instead to continue to hard-code versions into the script, and pay the price of updating them when Mac has new version names.

Since this all turns into a PR that will get human review I figure it's fine if things can go wrong. When it was sending PRs to https://github.com/Homebrew/homebrew-cask-versions which gets reviewed by someone else I was more conservative :)

**Pull request merged**
